export { useLogin } from './useLogin'
export { useRegister } from './useRegister'
export { useLogout } from './useLogout'
export { useUserDetails } from './useUserDetails'
export { useHotels } from './useHotels'
export { useHotelDetails } from './useHotelDetails'